name: Lint

on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    permissions:
      contents: read
      statuses: write
      pull-requests: write
    uses: LukeEvansTech/shared-workflows/.github/workflows/super-linter.yml@239610499ad65c397d8d90b1a139d041bf28598a # v1
    with:
      soft-launch: false
